package com.didispace.mapper;

import com.didispace.entity.Ask;

public interface AskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    int deleteByPrimaryKey(Integer askId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    int insert(Ask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    int insertSelective(Ask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    Ask selectByPrimaryKey(Integer askId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    int updateByPrimaryKeySelective(Ask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ask
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    int updateByPrimaryKey(Ask record);
}