package com.didispace.mapper;

import com.didispace.entity.TeachesKey;

public interface TeachesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaches
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    int deleteByPrimaryKey(TeachesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaches
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    int insert(TeachesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaches
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    int insertSelective(TeachesKey record);
}