package com.didispace.mapper;

import com.didispace.entity.TimeSlot;

public interface TimeSlotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_slot
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    int deleteByPrimaryKey(Integer timeSlotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_slot
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    int insert(TimeSlot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_slot
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    int insertSelective(TimeSlot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_slot
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    TimeSlot selectByPrimaryKey(Integer timeSlotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_slot
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    int updateByPrimaryKeySelective(TimeSlot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_slot
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    int updateByPrimaryKey(TimeSlot record);
}