package team.softwarede.confersys.entity;

public class BelongsToKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belongs_to.id
     *
     * @mbg.generated Sun Jun 02 00:31:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column belongs_to.user_id
     *
     * @mbg.generated Sun Jun 02 00:31:57 CST 2019
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belongs_to.id
     *
     * @return the value of belongs_to.id
     *
     * @mbg.generated Sun Jun 02 00:31:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belongs_to.id
     *
     * @param id the value for belongs_to.id
     *
     * @mbg.generated Sun Jun 02 00:31:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column belongs_to.user_id
     *
     * @return the value of belongs_to.user_id
     *
     * @mbg.generated Sun Jun 02 00:31:57 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column belongs_to.user_id
     *
     * @param userId the value for belongs_to.user_id
     *
     * @mbg.generated Sun Jun 02 00:31:57 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}