package team.softwarede.confersys.entity;

import java.util.Date;

public class Equipment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.equipment_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	private Integer equipmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.equipment_type_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	private Integer equipmentTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.meeting_room_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	private Integer meetingRoomId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.equipment_name
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	private String equipmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.store_time
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	private Date storeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column equipment.equipment_status
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	private String equipmentStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.equipment_id
	 * @return  the value of equipment.equipment_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public Integer getEquipmentId() {
		return equipmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.equipment_id
	 * @param equipmentId  the value for equipment.equipment_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public void setEquipmentId(Integer equipmentId) {
		this.equipmentId = equipmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.equipment_type_id
	 * @return  the value of equipment.equipment_type_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public Integer getEquipmentTypeId() {
		return equipmentTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.equipment_type_id
	 * @param equipmentTypeId  the value for equipment.equipment_type_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public void setEquipmentTypeId(Integer equipmentTypeId) {
		this.equipmentTypeId = equipmentTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.meeting_room_id
	 * @return  the value of equipment.meeting_room_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public Integer getMeetingRoomId() {
		return meetingRoomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.meeting_room_id
	 * @param meetingRoomId  the value for equipment.meeting_room_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public void setMeetingRoomId(Integer meetingRoomId) {
		this.meetingRoomId = meetingRoomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.equipment_name
	 * @return  the value of equipment.equipment_name
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public String getEquipmentName() {
		return equipmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.equipment_name
	 * @param equipmentName  the value for equipment.equipment_name
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public void setEquipmentName(String equipmentName) {
		this.equipmentName = equipmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.store_time
	 * @return  the value of equipment.store_time
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public Date getStoreTime() {
		return storeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.store_time
	 * @param storeTime  the value for equipment.store_time
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public void setStoreTime(Date storeTime) {
		this.storeTime = storeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column equipment.equipment_status
	 * @return  the value of equipment.equipment_status
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public String getEquipmentStatus() {
		return equipmentStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column equipment.equipment_status
	 * @param equipmentStatus  the value for equipment.equipment_status
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public void setEquipmentStatus(String equipmentStatus) {
		this.equipmentStatus = equipmentStatus;
	}
}