package team.softwarede.confersys.entity;

import java.util.Date;

public class Login {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.worker_id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    private String workerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.use_worker_id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    private String useWorkerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.login_time
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.worker_id
     *
     * @return the value of login.worker_id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public String getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.worker_id
     *
     * @param workerId the value for login.worker_id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public void setWorkerId(String workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.use_worker_id
     *
     * @return the value of login.use_worker_id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public String getUseWorkerId() {
        return useWorkerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.use_worker_id
     *
     * @param useWorkerId the value for login.use_worker_id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public void setUseWorkerId(String useWorkerId) {
        this.useWorkerId = useWorkerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.login_time
     *
     * @return the value of login.login_time
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.login_time
     *
     * @param loginTime the value for login.login_time
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}