package team.softwarede.confersys.entity;

import java.util.Date;

public class MeetingRoomSchedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_schedule.meeting_id
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    private Integer meetingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_schedule.meeting_room_id
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    private Integer meetingRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_schedule.begin_time
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_schedule.end_time
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_schedule.meeting_id
     *
     * @return the value of meeting_room_schedule.meeting_id
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public Integer getMeetingId() {
        return meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_schedule.meeting_id
     *
     * @param meetingId the value for meeting_room_schedule.meeting_id
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public void setMeetingId(Integer meetingId) {
        this.meetingId = meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_schedule.meeting_room_id
     *
     * @return the value of meeting_room_schedule.meeting_room_id
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public Integer getMeetingRoomId() {
        return meetingRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_schedule.meeting_room_id
     *
     * @param meetingRoomId the value for meeting_room_schedule.meeting_room_id
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public void setMeetingRoomId(Integer meetingRoomId) {
        this.meetingRoomId = meetingRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_schedule.begin_time
     *
     * @return the value of meeting_room_schedule.begin_time
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_schedule.begin_time
     *
     * @param beginTime the value for meeting_room_schedule.begin_time
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_schedule.end_time
     *
     * @return the value of meeting_room_schedule.end_time
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_schedule.end_time
     *
     * @param endTime the value for meeting_room_schedule.end_time
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}