package team.softwarede.confersys.entity;

public class Meeting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.id
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.topic
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    private String topic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.number
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.meeting_status_id
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    private String meetingStatusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.meeting_content
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    private String meetingContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.meeting_conclusion
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    private String meetingConclusion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting.apply_status_id
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    private String applyStatusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.id
     *
     * @return the value of meeting.id
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.id
     *
     * @param id the value for meeting.id
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.topic
     *
     * @return the value of meeting.topic
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.topic
     *
     * @param topic the value for meeting.topic
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public void setTopic(String topic) {
        this.topic = topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.number
     *
     * @return the value of meeting.number
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.number
     *
     * @param number the value for meeting.number
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.meeting_status_id
     *
     * @return the value of meeting.meeting_status_id
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public String getMeetingStatusId() {
        return meetingStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.meeting_status_id
     *
     * @param meetingStatusId the value for meeting.meeting_status_id
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public void setMeetingStatusId(String meetingStatusId) {
        this.meetingStatusId = meetingStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.meeting_content
     *
     * @return the value of meeting.meeting_content
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public String getMeetingContent() {
        return meetingContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.meeting_content
     *
     * @param meetingContent the value for meeting.meeting_content
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public void setMeetingContent(String meetingContent) {
        this.meetingContent = meetingContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.meeting_conclusion
     *
     * @return the value of meeting.meeting_conclusion
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public String getMeetingConclusion() {
        return meetingConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.meeting_conclusion
     *
     * @param meetingConclusion the value for meeting.meeting_conclusion
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public void setMeetingConclusion(String meetingConclusion) {
        this.meetingConclusion = meetingConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting.apply_status_id
     *
     * @return the value of meeting.apply_status_id
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public String getApplyStatusId() {
        return applyStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting.apply_status_id
     *
     * @param applyStatusId the value for meeting.apply_status_id
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    public void setApplyStatusId(String applyStatusId) {
        this.applyStatusId = applyStatusId;
    }
}