package team.softwarede.confersys.entity;

public class MeetingRoom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.id
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.capacity
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    private Integer capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.room_introduce
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    private String roomIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.room_number
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    private String roomNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.building
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    private String building;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.floor
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    private Integer floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.status_id
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    private String statusId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.id
     *
     * @return the value of meeting_room.id
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.id
     *
     * @param id the value for meeting_room.id
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.capacity
     *
     * @return the value of meeting_room.capacity
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.capacity
     *
     * @param capacity the value for meeting_room.capacity
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.room_introduce
     *
     * @return the value of meeting_room.room_introduce
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public String getRoomIntroduce() {
        return roomIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.room_introduce
     *
     * @param roomIntroduce the value for meeting_room.room_introduce
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public void setRoomIntroduce(String roomIntroduce) {
        this.roomIntroduce = roomIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.room_number
     *
     * @return the value of meeting_room.room_number
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.room_number
     *
     * @param roomNumber the value for meeting_room.room_number
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.building
     *
     * @return the value of meeting_room.building
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public String getBuilding() {
        return building;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.building
     *
     * @param building the value for meeting_room.building
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public void setBuilding(String building) {
        this.building = building;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.floor
     *
     * @return the value of meeting_room.floor
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.floor
     *
     * @param floor the value for meeting_room.floor
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.status_id
     *
     * @return the value of meeting_room.status_id
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.status_id
     *
     * @param statusId the value for meeting_room.status_id
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }
}