package team.softwarede.confersys.entity;

import java.util.Date;

public class MeetingRoomSchedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_schedule.id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_schedule.mee_id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    private Integer meeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_schedule.begin_time
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room_schedule.end_time
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_schedule.id
     *
     * @return the value of meeting_room_schedule.id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_schedule.id
     *
     * @param id the value for meeting_room_schedule.id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_schedule.mee_id
     *
     * @return the value of meeting_room_schedule.mee_id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public Integer getMeeId() {
        return meeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_schedule.mee_id
     *
     * @param meeId the value for meeting_room_schedule.mee_id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public void setMeeId(Integer meeId) {
        this.meeId = meeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_schedule.begin_time
     *
     * @return the value of meeting_room_schedule.begin_time
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_schedule.begin_time
     *
     * @param beginTime the value for meeting_room_schedule.begin_time
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room_schedule.end_time
     *
     * @return the value of meeting_room_schedule.end_time
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room_schedule.end_time
     *
     * @param endTime the value for meeting_room_schedule.end_time
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}