package team.softwarede.confersys.entity;

public class NoticesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.user_id
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.notification_id
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    private Integer notificationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.user_id
     *
     * @return the value of notices.user_id
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.user_id
     *
     * @param userId the value for notices.user_id
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.notification_id
     *
     * @return the value of notices.notification_id
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    public Integer getNotificationId() {
        return notificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.notification_id
     *
     * @param notificationId the value for notices.notification_id
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    public void setNotificationId(Integer notificationId) {
        this.notificationId = notificationId;
    }
}