package team.softwarede.confersys.entity;

public class NoticesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.user_id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.user_id
     *
     * @return the value of notices.user_id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.user_id
     *
     * @param userId the value for notices.user_id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.id
     *
     * @return the value of notices.id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.id
     *
     * @param id the value for notices.id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}