package team.softwarede.confersys.entity;

public class NoticesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.worker_id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    private String workerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.worker_id
     *
     * @return the value of notices.worker_id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public String getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.worker_id
     *
     * @param workerId the value for notices.worker_id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public void setWorkerId(String workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.id
     *
     * @return the value of notices.id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.id
     *
     * @param id the value for notices.id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }
}