package team.softwarede.confersys.entity;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notification_type
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    private String notificationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notification_detail
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    private String notificationDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notificationn_status
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    private String notificationnStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.refer_id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    private String referId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notification_type
     *
     * @return the value of notification.notification_type
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public String getNotificationType() {
        return notificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notification_type
     *
     * @param notificationType the value for notification.notification_type
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public void setNotificationType(String notificationType) {
        this.notificationType = notificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notification_detail
     *
     * @return the value of notification.notification_detail
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public String getNotificationDetail() {
        return notificationDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notification_detail
     *
     * @param notificationDetail the value for notification.notification_detail
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public void setNotificationDetail(String notificationDetail) {
        this.notificationDetail = notificationDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notificationn_status
     *
     * @return the value of notification.notificationn_status
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public String getNotificationnStatus() {
        return notificationnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notificationn_status
     *
     * @param notificationnStatus the value for notification.notificationn_status
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public void setNotificationnStatus(String notificationnStatus) {
        this.notificationnStatus = notificationnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.refer_id
     *
     * @return the value of notification.refer_id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public String getReferId() {
        return referId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.refer_id
     *
     * @param referId the value for notification.refer_id
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    public void setReferId(String referId) {
        this.referId = referId;
    }
}