package team.softwarede.confersys.entity;

public class Notification {

    private Integer id;

    private String notificationType;

    private String notificationDetail;

    private String notificationStatus;

    /**
     * 当通知类型为：新会议、审核结果、请假，该referId都是指对应的会议编号
     * 
     */
    private String referId;
    

    public String getReferId() {
		return referId;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notification_type
     *
     * @return the value of notification.notification_type
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    public String getNotificationType() {
        return notificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notification_type
     *
     * @param notificationType the value for notification.notification_type
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    public void setNotificationType(String notificationType) {
        this.notificationType = notificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notification_detail
     *
     * @return the value of notification.notification_detail
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    public String getNotificationDetail() {
        return notificationDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notification_detail
     *
     * @param notificationDetail the value for notification.notification_detail
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    public void setNotificationDetail(String notificationDetail) {
        this.notificationDetail = notificationDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notificationn_status
     *
     * @return the value of notification.notificationn_status
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    public void setReferId(String referId) {
        this.referId = referId;
    }

	public String getNotificationStatus() {
		return notificationStatus;
	}

	public void setNotificationStatus(String notificationStatus) {
		this.notificationStatus = notificationStatus;
	}
}