package team.softwarede.confersys.entity;

public class ParticipatesMeetingKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participates_meeting.id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participates_meeting.mee_id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    private Integer meeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participates_meeting.id
     *
     * @return the value of participates_meeting.id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participates_meeting.id
     *
     * @param id the value for participates_meeting.id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participates_meeting.mee_id
     *
     * @return the value of participates_meeting.mee_id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public Integer getMeeId() {
        return meeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participates_meeting.mee_id
     *
     * @param meeId the value for participates_meeting.mee_id
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    public void setMeeId(Integer meeId) {
        this.meeId = meeId;
    }
}