package team.softwarede.confersys.entity;

public class ParticipatesKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column participates.user_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column participates.meeting_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	private Integer meetingId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column participates.user_id
	 * @return  the value of participates.user_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column participates.user_id
	 * @param userId  the value for participates.user_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column participates.meeting_id
	 * @return  the value of participates.meeting_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public Integer getMeetingId() {
		return meetingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column participates.meeting_id
	 * @param meetingId  the value for participates.meeting_id
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	public void setMeetingId(Integer meetingId) {
		this.meetingId = meetingId;
	}
}