package team.softwarede.confersys.entity;

import java.util.Date;

public class Schedule extends ScheduleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.begin_time
     *
     * @mbg.generated Thu May 30 15:31:38 CST 2019
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.end_time
     *
     * @mbg.generated Thu May 30 15:31:38 CST 2019
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.begin_time
     *
     * @return the value of schedule.begin_time
     *
     * @mbg.generated Thu May 30 15:31:38 CST 2019
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.begin_time
     *
     * @param beginTime the value for schedule.begin_time
     *
     * @mbg.generated Thu May 30 15:31:38 CST 2019
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.end_time
     *
     * @return the value of schedule.end_time
     *
     * @mbg.generated Thu May 30 15:31:38 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.end_time
     *
     * @param endTime the value for schedule.end_time
     *
     * @mbg.generated Thu May 30 15:31:38 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}