package team.softwarede.confersys.entity;

public class User {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.worker_id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    private String workerId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.log_worker_id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    private String logWorkerId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.ide_id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    private String ideId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.rol_id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    private String rolId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.sex
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    private String sex;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.telephone
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    private String telephone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    private String email;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.worker_id
     * @return  the value of user.worker_id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public String getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.worker_id
     * @param workerId  the value for user.worker_id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public void setWorkerId(String workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.log_worker_id
     * @return  the value of user.log_worker_id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public String getLogWorkerId() {
        return logWorkerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.log_worker_id
     * @param logWorkerId  the value for user.log_worker_id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public void setLogWorkerId(String logWorkerId) {
        this.logWorkerId = logWorkerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
     * @return  the value of user.id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
     * @param id  the value for user.id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.ide_id
     * @return  the value of user.ide_id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public String getIdeId() {
        return ideId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.ide_id
     * @param ideId  the value for user.ide_id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public void setIdeId(String ideId) {
        this.ideId = ideId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.rol_id
     * @return  the value of user.rol_id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public String getRolId() {
        return rolId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.rol_id
     * @param rolId  the value for user.rol_id
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public void setRolId(String rolId) {
        this.rolId = rolId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
     * @return  the value of user.name
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
     * @param name  the value for user.name
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.sex
     * @return  the value of user.sex
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.sex
     * @param sex  the value for user.sex
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.telephone
     * @return  the value of user.telephone
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.telephone
     * @param telephone  the value for user.telephone
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
     * @return  the value of user.email
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
     * @param email  the value for user.email
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
     * @return  the value of user.password
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
     * @param password  the value for user.password
     * @mbg.generated  Sat May 18 16:16:01 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }
}