package team.softwarede.confersys.mapper;

import org.apache.ibatis.annotations.Mapper;

import team.softwarede.confersys.entity.BelongsToKey;

@Mapper
public interface BelongsToMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belongs_to
     *
     * @mbg.generated Sun Jun 02 00:42:02 CST 2019
     */
    int deleteByPrimaryKey(BelongsToKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belongs_to
     *
     * @mbg.generated Sun Jun 02 00:42:02 CST 2019
     */
    int insert(BelongsToKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table belongs_to
     *
     * @mbg.generated Sun Jun 02 00:42:02 CST 2019
     */
    int insertSelective(BelongsToKey record);
}