package team.softwarede.confersys.mapper;

import team.softwarede.confersys.entity.EquipmentType;

public interface EquipmentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int insert(EquipmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int insertSelective(EquipmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    EquipmentType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int updateByPrimaryKeySelective(EquipmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int updateByPrimaryKey(EquipmentType record);
}