package team.softwarede.confersys.mapper;

import team.softwarede.confersys.entity.Identity;

public interface IdentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    int insert(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    int insertSelective(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    Identity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    int updateByPrimaryKeySelective(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Wed May 29 09:02:50 CST 2019
     */
    int updateByPrimaryKey(Identity record);
}