package team.softwarede.confersys.mapper;

import team.softwarede.confersys.entity.Identity;

public interface IdentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    int insert(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    int insertSelective(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    Identity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    int updateByPrimaryKeySelective(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    int updateByPrimaryKey(Identity record);
}