package team.softwarede.confersys.mapper;

import team.softwarede.confersys.entity.Identity;
import org.apache.ibatis.annotations.Mapper;


@Mapper
public interface IdentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    int insert(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    int insertSelective(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    Identity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    int updateByPrimaryKeySelective(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity
     *
     * @mbg.generated Sun May 26 09:58:09 CST 2019
     */
    int updateByPrimaryKey(Identity record);
}