package team.softwarede.confersys.mapper;

import org.apache.ibatis.annotations.Mapper;

import team.softwarede.confersys.entity.LeaveApplication;
import team.softwarede.confersys.entity.LeaveApplicationKey;

@Mapper
public interface LeaveApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_application
     *
     * @mbg.generated Sun Jun 02 00:45:14 CST 2019
     */
    int deleteByPrimaryKey(LeaveApplicationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_application
     *
     * @mbg.generated Sun Jun 02 00:45:14 CST 2019
     */
    int insert(LeaveApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_application
     *
     * @mbg.generated Sun Jun 02 00:45:14 CST 2019
     */
    int insertSelective(LeaveApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_application
     *
     * @mbg.generated Sun Jun 02 00:45:14 CST 2019
     */
    LeaveApplication selectByPrimaryKey(LeaveApplicationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_application
     *
     * @mbg.generated Sun Jun 02 00:45:14 CST 2019
     */
    int updateByPrimaryKeySelective(LeaveApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_application
     *
     * @mbg.generated Sun Jun 02 00:45:14 CST 2019
     */
    int updateByPrimaryKey(LeaveApplication record);
}