package team.softwarede.confersys.mapper;

import team.softwarede.confersys.entity.LeaveApplication;

public interface LeaveApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_application
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int deleteByPrimaryKey(Integer meetingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_application
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int insert(LeaveApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_application
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int insertSelective(LeaveApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_application
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    LeaveApplication selectByPrimaryKey(Integer meetingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_application
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int updateByPrimaryKeySelective(LeaveApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_application
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int updateByPrimaryKey(LeaveApplication record);
}