package team.softwarede.confersys.mapper;

import team.softwarede.confersys.entity.Login;

public interface LoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    int deleteByPrimaryKey(String workerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    int insert(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    int insertSelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    Login selectByPrimaryKey(String workerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    int updateByPrimaryKeySelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbg.generated Sat May 18 16:16:01 CST 2019
     */
    int updateByPrimaryKey(Login record);
}