package team.softwarede.confersys.mapper;

import org.apache.ibatis.annotations.Mapper;

import team.softwarede.confersys.entity.Meeting;

@Mapper
public interface MeetingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int insert(Meeting record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int insertSelective(Meeting record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	Meeting selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int updateByPrimaryKeySelective(Meeting record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table meeting
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int updateByPrimaryKey(Meeting record);
}