package team.softwarede.confersys.mapper;

import team.softwarede.confersys.entity.NoticesKey;

public interface NoticesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    int deleteByPrimaryKey(NoticesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    int insert(NoticesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notices
     *
     * @mbg.generated Thu May 30 09:12:43 CST 2019
     */
    int insertSelective(NoticesKey record);
}