package team.softwarede.confersys.mapper;

import org.apache.ibatis.annotations.Mapper;

import team.softwarede.confersys.entity.NoticesKey;

@Mapper
public interface NoticesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notices
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int deleteByPrimaryKey(NoticesKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notices
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int insert(NoticesKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table notices
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int insertSelective(NoticesKey record);
}