package team.softwarede.confersys.mapper;

import team.softwarede.confersys.entity.ParticipatesMeetingKey;

public interface ParticipatesMeetingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participates_meeting
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int deleteByPrimaryKey(ParticipatesMeetingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participates_meeting
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int insert(ParticipatesMeetingKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participates_meeting
     *
     * @mbg.generated Thu May 30 16:48:49 CST 2019
     */
    int insertSelective(ParticipatesMeetingKey record);
}