package team.softwarede.confersys.mapper;

import org.apache.ibatis.annotations.Mapper;

import team.softwarede.confersys.entity.Participates;
import team.softwarede.confersys.entity.ParticipatesKey;

@Mapper
public interface ParticipatesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table participates
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int deleteByPrimaryKey(ParticipatesKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table participates
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int insert(Participates record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table participates
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int insertSelective(Participates record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table participates
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	Participates selectByPrimaryKey(ParticipatesKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table participates
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int updateByPrimaryKeySelective(Participates record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table participates
	 * @mbg.generated  Sat Jun 01 21:30:06 CST 2019
	 */
	int updateByPrimaryKey(Participates record);
}