package team.softwarede.confersys.mapper;

import org.apache.ibatis.annotations.Mapper;

import team.softwarede.confersys.entity.User;


@Mapper
public interface UserMapper {

    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu May 30 15:31:38 CST 2019
	 */
	int deleteByPrimaryKey(String userId);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu May 30 15:31:38 CST 2019
	 */
	int insert(User record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu May 30 15:31:38 CST 2019
	 */
	int insertSelective(User record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu May 30 15:31:38 CST 2019
	 */
	User selectByPrimaryKey(String userId);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu May 30 15:31:38 CST 2019
	 */
	int updateByPrimaryKeySelective(User record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Thu May 30 15:31:38 CST 2019
	 */
	int updateByPrimaryKey(User record);


	int deleteByPrimaryKey(String userId);


    int insert(User record);

 
    int insertSelective(User record);


    User selectByPrimaryKey(String userId);

    User selectByIdByIdentityId(String uId, Integer identityId);

    int updateByPrimaryKeySelective(User record);


    int updateByPrimaryKey(User record);
}