package com.didispace.entity;

import java.util.Date;

public class Ask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.ask_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    private Integer askId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.s_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.course_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.start_leave
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    private Date startLeave;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.end_leave
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    private Date endLeave;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ask.reason
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.ask_id
     *
     * @return the value of ask.ask_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public Integer getAskId() {
        return askId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.ask_id
     *
     * @param askId the value for ask.ask_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public void setAskId(Integer askId) {
        this.askId = askId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.s_id
     *
     * @return the value of ask.s_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.s_id
     *
     * @param sId the value for ask.s_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.course_id
     *
     * @return the value of ask.course_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.course_id
     *
     * @param courseId the value for ask.course_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.start_leave
     *
     * @return the value of ask.start_leave
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public Date getStartLeave() {
        return startLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.start_leave
     *
     * @param startLeave the value for ask.start_leave
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public void setStartLeave(Date startLeave) {
        this.startLeave = startLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.end_leave
     *
     * @return the value of ask.end_leave
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public Date getEndLeave() {
        return endLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.end_leave
     *
     * @param endLeave the value for ask.end_leave
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public void setEndLeave(Date endLeave) {
        this.endLeave = endLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ask.reason
     *
     * @return the value of ask.reason
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ask.reason
     *
     * @param reason the value for ask.reason
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason;
    }
}