package com.didispace.entity;

public class Record extends RecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.attendance
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    private String attendance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.attendance
     *
     * @return the value of record.attendance
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public String getAttendance() {
        return attendance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.attendance
     *
     * @param attendance the value for record.attendance
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public void setAttendance(String attendance) {
        this.attendance = attendance;
    }
}