package com.didispace.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_id
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_name
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_passwd
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    private String sPasswd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_id
     *
     * @return the value of student.s_id
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_id
     *
     * @param sId the value for student.s_id
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_name
     *
     * @return the value of student.s_name
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_name
     *
     * @param sName the value for student.s_name
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    public void setsName(String sName) {
        this.sName = sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_passwd
     *
     * @return the value of student.s_passwd
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    public String getsPasswd() {
        return sPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_passwd
     *
     * @param sPasswd the value for student.s_passwd
     *
     * @mbg.generated Tue Apr 23 16:09:01 CST 2019
     */
    public void setsPasswd(String sPasswd) {
        this.sPasswd = sPasswd;
    }
}