package com.didispace.entity;

public class TakesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takes.s_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takes.course_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takes.s_id
     *
     * @return the value of takes.s_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takes.s_id
     *
     * @param sId the value for takes.s_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takes.course_id
     *
     * @return the value of takes.course_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takes.course_id
     *
     * @param courseId the value for takes.course_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}