package com.didispace.entity;

public class TeachesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaches.t_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    private Integer tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaches.course_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaches.t_id
     *
     * @return the value of teaches.t_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaches.t_id
     *
     * @param tId the value for teaches.t_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaches.course_id
     *
     * @return the value of teaches.course_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaches.course_id
     *
     * @param courseId the value for teaches.course_id
     *
     * @mbg.generated Tue Apr 23 16:27:29 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}