package com.didispace.entity;

public class User2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2.id
     *
     * @mbg.generated Sat Apr 20 11:35:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2.name
     *
     * @mbg.generated Sat Apr 20 11:35:46 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2.age
     *
     * @mbg.generated Sat Apr 20 11:35:46 CST 2019
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2.id
     *
     * @return the value of user2.id
     *
     * @mbg.generated Sat Apr 20 11:35:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2.id
     *
     * @param id the value for user2.id
     *
     * @mbg.generated Sat Apr 20 11:35:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2.name
     *
     * @return the value of user2.name
     *
     * @mbg.generated Sat Apr 20 11:35:46 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2.name
     *
     * @param name the value for user2.name
     *
     * @mbg.generated Sat Apr 20 11:35:46 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2.age
     *
     * @return the value of user2.age
     *
     * @mbg.generated Sat Apr 20 11:35:46 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2.age
     *
     * @param age the value for user2.age
     *
     * @mbg.generated Sat Apr 20 11:35:46 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}